/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2022-11-09 15:54:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Modelo.Connection2;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Login</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <table>\n");
      out.write("            <tr>\n");
      out.write("                <td>Usuario:</td>\n");
      out.write("                <td><input type=\"text\" id=\"user\"></td>\n");
      out.write("                <td><label id=\"userError\" style=\"display: none; color: rgb(255, 0, 0);\">Incorrecto</label></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>Contraseña:</td><td><input type=\"password\" id=\"psw\"></td>\n");
      out.write("                <td><label id=\"passError\" style=\"display: none; color: rgb(255, 0, 0);\">Incorrecto</label></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td><input type=\"submit\" value=\"Mandale\" onclick=\"validarDatos()\"></td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("    </body>\n");
      out.write("    <script>\n");
      out.write("        function validarDatos() {\n");
      out.write("            var user = document.getElementById(\"user\");\n");
      out.write("            var psw = document.getElementById(\"psw\");\n");
      out.write("            var userErr = document.getElementById(\"userError\");\n");
      out.write("            var passErr = document.getElementById(\"passError\");\n");
      out.write("            var error = false;\n");
      out.write("            limpiarError();\n");
      out.write("\n");
      out.write("            if (user.value === null || user.value === \"\") {\n");
      out.write("                userErr.style.display = \"inline\";\n");
      out.write("                error = true;\n");
      out.write("            }\n");
      out.write("            if (psw.value === null || psw.value === \"\" || psw.value.length < 6) {\n");
      out.write("                passErr.style.display = \"inline\";\n");
      out.write("                error = true;\n");
      out.write("            }\n");
      out.write("            if (!error) {\n");
      out.write("                window.location = \"login.jsp?usuario=\" + user.value + \"&clave=\" + psw.value;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        function limpiarError() {\n");
      out.write("            var userErr = document.getElementById(\"userError\");\n");
      out.write("            var passErr = document.getElementById(\"passError\");\n");
      out.write("\n");
      out.write("            userErr.style.display = \"none\";\n");
      out.write("            passErr.style.display = \"none\";\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    ");

        
        if(request.getParameter("usuario") != null){
            String usuario = request.getParameter("usuario");
            String clave = request.getParameter("clave");
            
            String id = (String) request.getParameter("id");
            Connection2 cn = new Connection2();
            java.sql.Connection con = cn.getConnection();
            java.sql.Statement state = con.createStatement();
            String query = "SELECT * FROM usuario WHERE usuario='" + usuario + "';";
            java.sql.ResultSet rs = state.executeQuery(query);
            
            int idnum; 
            String user, psw; 
            
            while (rs.next()){
                idnum = rs.getInt(1);
                user = rs.getString(2);
                psw = rs.getString(3);
                
                if (clave.equalsIgnoreCase(psw)){
                    response.sendRedirect("abmusuario.jsp");
                }
            }
        }
            

    
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
