/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2022-10-16 21:12:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>JSP</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            function aceptar(){\n");
      out.write("\n");
      out.write("                var usuario, clave, navegador;\n");
      out.write("                usuario = document.getElementById('idusuario').value;\n");
      out.write("                clave = document.getElementById('idclave').value;\n");
      out.write("                navegador = navigator.appName;\n");
      out.write("\n");
      out.write("                if(usuario == ''){\n");
      out.write("                    alert(\"Ingrese su nombre de Usuario\");\n");
      out.write("                    return false;\n");
      out.write("                }\n");
      out.write("                if(clave == ''){\n");
      out.write("                    alert(\"Ingrese su clave de Ingreso\");\n");
      out.write("                    return false;\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                ajax = (window.ActiveXObject) ? new ActiveXObject('Microsoft.XMLHTTP') : new XMLHttpRequest();\n");
      out.write("                if (ajax) {\n");
      out.write("\n");
      out.write("                    s = 'cu=login';\n");
      out.write("                    s += '&usuario=' + usuario;\n");
      out.write("                    s += '&clave=' + clave;\n");
      out.write("                    s += '&navegador=' + navegador;\n");
      out.write("                    alert(s);\n");
      out.write("                    ajax.onreadystatechange = enviar;\n");
      out.write("                    ajax.open('POST', '");
      out.print(response.encodeURL("servlet/ServletJSP?"));
      out.write("'+s, true);\n");
      out.write("                    ajax.send(null);\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function enviar() {\n");
      out.write("                if (ajax.readyState == 4 ) {\n");
      out.write("                    if (ajax.status == 200) {\n");
      out.write("                        datos = ajax.responseText;\n");
      out.write("\n");
      out.write("                        ok = datos.split('-');\n");
      out.write("                        //alert(ok);\n");
      out.write("                        if(ok[0] == 1) {\n");
      out.write("                            document.location.href = \"vista/home.jsp\";\n");
      out.write("                        }\n");
      out.write("                        else {\n");
      out.write("                            alert('Su usuario y/o contraseña es incorrecta o ha caducado. Por favor vuelva a intentarlo o comuniquese con el Administrador.');\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                    else {\n");
      out.write("                        alert(ajax.status + ': No se pudo cargar la página. Por favor vuelva a intentarlo');\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            // presiono enter\n");
      out.write("            var tecla;\n");
      out.write("            function capturaTecla(e)\n");
      out.write("            {\n");
      out.write("                if(document.all)\n");
      out.write("                    tecla=event.keyCode;\n");
      out.write("                else\n");
      out.write("                {\n");
      out.write("                    tecla=e.which;\n");
      out.write("                }\n");
      out.write("                if(tecla==13)\n");
      out.write("                {\n");
      out.write("                    aceptar();\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            document.onkeydown = capturaTecla;\n");
      out.write("        </script>\n");
      out.write("        \n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("        <table align=\"center\" width=\"100%\">\n");
      out.write("            <tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>Usuario</td>\n");
      out.write("                <td><input value=\"\" type=\"text\" name=\"usuario\" id=\"idusuario\"></input></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>Clave</td>\n");
      out.write("                <td><input value=\"\" type=\"password\" name=\"clave\" id=\"idclave\"></input></td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("        <br>\n");
      out.write("        <table width=\"100%\">\n");
      out.write("            <tr>\n");
      out.write("                <td align=\"center\"><input type=\"button\" onclick=\"aceptar();\" value=\"Aceptar\" style=\"font-family: verdana; font-size: 14px; color: #150567; border-color: #92c7c7; background-color: #92c7c7\" border=\"0\"></input></td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("        <br>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
