/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2022-11-08 22:06:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Catedra</title>\n");
      out.write("    </head>\n");
      out.write("    <style>\n");
      out.write("        table{\n");
      out.write("            margin-left: 1%;\n");
      out.write("            margin-top: 1%;\n");
      out.write("        }\n");
      out.write("        th{\n");
      out.write("            border: 1px solid black;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            padding: 15px;\n");
      out.write("            background-color: dimgray;\n");
      out.write("            color:white;\n");
      out.write("        }\n");
      out.write("        table, td {\n");
      out.write("            border: 1px solid black;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            padding: 15px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <body >\n");
      out.write("        ");

            String JDBC_DRIVER = "com.mysql.jdbc.Driver";
            Class.forName(JDBC_DRIVER);
            String url = "jdbc:mysql://localhost:3306/escuela?serverTimezone=UTC";
            java.sql.Connection miConexion = java.sql.DriverManager.getConnection(url, "root", "mysql");
            java.sql.Statement miStatement = miConexion.createStatement();
            String query = "select * from catedra;";
            ResultSet rs = miStatement.executeQuery(query);
        
      out.write("\n");
      out.write("        <form action =\"index.jsp\" method =\"post\">\n");
      out.write("            <select name=\"input_user\" id=\"input_user\" onchange=\"this.form.submit()\">\n");
      out.write("                <option value =\"default\">Seleccion una catedra</option>\n");
      out.write("                ");
        while (rs.next()) {
                
      out.write("\n");
      out.write("\n");
      out.write("                <option value=\"");
 out.println(rs.getLong(1));
      out.write('"');
      out.write('>');
 out.println(rs.getString(2));
      out.write("</option>\n");
      out.write("                ");
}
      out.write("\n");
      out.write("            </select>\n");
      out.write("            \n");
      out.write("            <!-- <button type=\"submit\">Submit</button>-->\n");
      out.write("\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        ");


            if (request.getParameter("input_user") != null) {
                String codigoCatedra = (String) request.getParameter("input_user");
                codigoCatedra = codigoCatedra.substring(0, 2);
                query = "select alumno.nombre, alumno.apellido"
                        + " from catedra"
                        + " inner join catedra_alumno on catedra.codigo = catedra_alumno.codigoCatedra "
                        + " inner join alumno on catedra_alumno.legajoAlumno = alumno.legajo"
                        + " where catedra.codigo = " + codigoCatedra + ";";
                rs = miStatement.executeQuery(query);

            }

        
      out.write("\n");
      out.write("        <form action =\"index.jsp\" method=\"post\">\n");
      out.write("            <table border=\"1\" width=\"50%\" style =\"border-collapse: collapse\">\n");
      out.write("                <tr>\n");
      out.write("                    <th> ");
 out.println("NOMBRE");
      out.write("</th>\n");
      out.write("                    <th> ");
 out.println("Apellido");
      out.write("</th>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                ");

                    while (rs.next()) {
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
 out.println(rs.getString(1)); 
      out.write("</td>\n");
      out.write("                    <td>");
 out.println(rs.getString(2)); 
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                ");
 }
      out.write("\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("            <!-- <button type=\"submit\">Submit</button>-->\n");
      out.write("\n");
      out.write("        </form>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
