/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2022-11-07 23:07:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.utn.managers.AgendaManager;
import com.utn.managers.Conexion;
import com.utn.apprest.AgendaRest;
import java.util.ArrayList;
import java.util.List;
import com.utn.modelo.Agenda;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");


      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <link href=\"bootstrap-5.2.2-dist/css/bootstrap.min.css\" rel=\"stylesheet\" crossorigin=\"anonymous\">\r\n");
      out.write("        <script src=\"bootstrap-5.2.2-dist/js/bootstrap.bundle.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Agenda</title>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body onload=\"getContactos()\">\r\n");
      out.write("        <h2>AGENDA</h2>\r\n");
      out.write("        <div id=\"agenda\" style=\"width: 50%;\" class=\"container text-left\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">ID (solo lectura)</div>\r\n");
      out.write("                <div class=\"col\"><input type=\"number\" id=\"id\" name=\"id\" readonly/></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">Nombre</div>\r\n");
      out.write("                <div class=\"col\"><input type=\"text\" id=\"nombre\" name=\"nombre\" required /></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">Apellido</div>\r\n");
      out.write("                <div class=\"col\"><input type=\"text\" id=\"apellido\" name=\"apellido\" required/></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">Teléfono</div>\r\n");
      out.write("                <div class=\"col\"><input type=\"number\" id=\"telefono\" name=\"telefono\" required /></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">Dirección</div>\r\n");
      out.write("                <div class=\"col\"><input type=\"text\" id=\"direccion\" name=\"direccion\" required/></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <div id=\"txtMensaje\" style=\"color: rgb(0, 153, 255); font-weight: bold;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <button onclick=\"limpiarDatos()\">LIMPIAR</button>\r\n");
      out.write("                    <button onclick=\"insertarActualizarDatos()\">GUARDAR</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <hr style=\"border: white\">\r\n");
      out.write("        <div id=\"listaEmpleados\" class=\"container text-center\">\r\n");
      out.write("            ");

                //AgendaManager magendas = new AgendaManager();
                //List<Agenda> agendas = new ArrayList<>();
                //agendas = magendas.getAll();
                //for(Agenda a : agendas){
                
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col\">");
 //String.valueOf(a.getId()); 
      out.write(" </div>\r\n");
      out.write("                    <div class=\"col\">");
 //String.valueOf(a.getId()); 
      out.write(" </div>\r\n");
      out.write("                    <div class=\"col\">");
 //String.valueOf(a.getId()); 
      out.write(" </div>\r\n");
      out.write("                    <div class=\"col\">");
 //String.valueOf(a.getId()); 
      out.write(" </div>\r\n");
      out.write("                    <div class=\"col\">");
 //String.valueOf(a.getId()); 
      out.write(" </div>\r\n");
      out.write("                    <div class=\"col\" style=\"cursor:pointer; color:green\">Editar</div>\r\n");
      out.write("                    <div class=\"col\" style=\"cursor:pointer; color:red\">Eliminar</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");

                //}
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
