/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author pc
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista1
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jP1 = new javax.swing.JPanel();
        jTF1 = new javax.swing.JTextField();
        jB0 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jBDot = new javax.swing.JButton();
        jBReset = new javax.swing.JButton();
        jBEqual = new javax.swing.JButton();
        jBNeg = new javax.swing.JButton();
        jBOp1 = new javax.swing.JButton();
        jBOp2 = new javax.swing.JButton();
        jBOp3 = new javax.swing.JButton();
        jBOp4 = new javax.swing.JButton();
        jBOp5 = new javax.swing.JButton();
        jBOp6 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jP1.setBackground(new java.awt.Color(151, 191, 175));
        jP1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jTF1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTF1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTF1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray));
        jTF1.setEnabled(false);

        jB0.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jB0.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB0.setText("0");
        jB0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jB1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB1.setText("1");
        jB1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jB2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB2.setText("2");
        jB2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jB3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB3.setText("3");
        jB3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jB4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB4.setText("4");
        jB4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jB5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB5.setText("5");
        jB5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jB6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB6.setText("6");
        jB6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jB7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB7.setText("7");
        jB7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jB8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB8.setText("8");
        jB8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB9.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jB9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jB9.setText("9");
        jB9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBDot.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jBDot.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBDot.setText(".");
        jBDot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBDot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBReset.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jBReset.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBReset.setText("C");
        jBReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBEqual.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jBEqual.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBEqual.setText("=");
        jBEqual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBEqual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBNeg.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jBNeg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBNeg.setText("+/-");
        jBNeg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBNeg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBOp1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jBOp1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBOp1.setText("+");
        jBOp1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBOp1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBOp2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jBOp2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBOp2.setText("-");
        jBOp2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBOp2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBOp3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jBOp3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBOp3.setText("*");
        jBOp3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBOp3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBOp4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jBOp4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBOp4.setText("/");
        jBOp4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBOp4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBOp5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jBOp5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBOp5.setText("^");
        jBOp5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBOp5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBOp6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jBOp6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBOp6.setText("^(-1)");
        jBOp6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBOp6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jP1Layout = new javax.swing.GroupLayout(jP1);
        jP1.setLayout(jP1Layout);
        jP1Layout.setHorizontalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF1)
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP1Layout.createSequentialGroup()
                                .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP1Layout.createSequentialGroup()
                                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jP1Layout.createSequentialGroup()
                                        .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jP1Layout.createSequentialGroup()
                                        .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jP1Layout.createSequentialGroup()
                                        .addComponent(jBDot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP1Layout.createSequentialGroup()
                                .addComponent(jBOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP1Layout.createSequentialGroup()
                                .addComponent(jBOp5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBOp6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP1Layout.createSequentialGroup()
                                .addComponent(jBOp3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBOp4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP1Layout.createSequentialGroup()
                                .addComponent(jBNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jP1Layout.setVerticalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBDot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBOp3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBOp4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBOp5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBOp6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jB0;
    public javax.swing.JButton jB1;
    public javax.swing.JButton jB2;
    public javax.swing.JButton jB3;
    public javax.swing.JButton jB4;
    public javax.swing.JButton jB5;
    public javax.swing.JButton jB6;
    public javax.swing.JButton jB7;
    public javax.swing.JButton jB8;
    public javax.swing.JButton jB9;
    public javax.swing.JButton jBDot;
    public javax.swing.JButton jBEqual;
    public javax.swing.JButton jBNeg;
    public javax.swing.JButton jBOp1;
    public javax.swing.JButton jBOp2;
    public javax.swing.JButton jBOp3;
    public javax.swing.JButton jBOp4;
    public javax.swing.JButton jBOp5;
    public javax.swing.JButton jBOp6;
    public javax.swing.JButton jBReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jP1;
    public javax.swing.JTextField jTF1;
    // End of variables declaration//GEN-END:variables
}
